### PR TITLE
Support for Microsoft Edge.

### PR DESCRIPTION
**Pull request by masta**
BrowserSelector made my life a lot easier but I needed it to support Microsoft Edge so here's a pull request in case you're interested in this change.

### CODE REVIEW

**Comment by DanTup** [comment]
Thanks for this; I haven't updated my Desktop yet, so hadn't been able to test it.

Is the reason for these changes simply to allow using `edge` instead of `microsoft-edge` in the config file, or is there more to it? The `[browsers]` section already allows you to assign short names to browsers, so I don't think there's huge value in being able to use `edge` instead of `microsoft-edge` (in fact, I think it's slightly confusing having this "magic", because what's in the browser section doesn't match the command a user could use to launch the browser)?

Eg., can't you just do this:

```
[browsers]
edge = microsoft-edge
```

and not need any code changes?

**Comment by masta** [comment]
I made a few tests before starting Visual Studio/forking. 
The problem is the statement starting the process: `Process.Start(preference.Browser.Location, url);`
I never got it running with using `microsoft-edge:` as location. It unfortunately just opens an empty tab in Edge.  
Maybe indeed a simpler change would also be possible to support Edge.
Do you have any idea?

**Comment by DanTup** [comment]
Sorry, I didn't see the colon in your command, I thought you were just launching `microsoft-edge (url)`. Didn't realise Edge was weird like that :(

I guess it does need special handling; but maybe it can be done more generically, like a dictionary for aliases and a format string for the command?

```
var specialCommands = new Dictionary<string, string> {
    { "edge", "microsoft-edge:{0}" }
}
```

I don't know if there would be any other browsers that need special handling like this, I wonder if this is some new plan from MS to use protocol handlers for things (this might allow hyperlinks in one browser to target another, like the handling of `mailto:`!?)

**Comment by masta** [comment]
No problem. Indeed I could have started my message with stating that Edge is 'weird' :-)
This is just because Edge is one of these modern apps (Windows 10 UWP app).  
I don't know whether such a dictionary is required, but I agree that the configuration `edge = edge` is ugly. Maybe just `edge` could be given?
Or how would you set up the configuration if such a dictionary is used?

**Comment by DanTup** [comment]
Something like:

```
if (specialCommands.ContainsKey(preference.Browser.Name))
    Process.Start(string.Format(specialCommands[preference.Browser.Name], url));
else
    Process.Start(preference.Browser.Location, url)
```

?

**Comment by masta** [comment]
I was asking about the configuration in the INI file. Would this be fine for you? 

	[browsers]
	edge
	chrome = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
	ff = C:\Program Files (x86)\Mozilla Firefox\firefox.exe
	ie = iexplore.exe

The code you suggest seems fine and like that it should work.

**Comment by DanTup** [comment]
Sorry, I understand what you mean now.

I think that would be fine, or even `edge=` (this seems to be how Mercurial handles built-in extensions, so possibly it's an existing convention).

**Comment by masta** [comment]
I've updated the pull request with this change. Hope it's alright now. 
An alternative would have been to handle it all in the INI file, like so:  

	[browsers]
	edge = micrsoft-edge:{0}
	chrome = C:\Program Files (x86)\Google\Chrome\Application\chrome.exe {0}
	ff = C:\Program Files (x86)\Mozilla Firefox\firefox.exe {0}
	ie = iexplore.exe {0}
But this would break existing configurations.

**Comment by DanTup** [comment]
This all looks fine to me. I like your last idea too (we could assume " {0}" on the end if the user didn't provide it in the console), but it would slightly complicate things because of spaces needing quoting.

I'll build and upload a new binary with these changes when I get a moment on the desktop.

Thanks!

**Comment by masta** [comment]
Well thank you Danny for this great idea. Your application fixes a very long time problem for me and certainly a lot of others too.

**Pull request merged**
